spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itsv?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=UTC&useSSL=false
    hikari:
      username: root
      password: itsv
      # >= 6.x com.mysql.cj.jdbc.Driver
      # <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8080
